### ISSUE TITLE
English branch?

### ISSUE THREAD

**Issue by CodeMeZone** [morais5/QBCore-Morais#11]
I would love to push some stuff the only issue is it's all in English, I really like this base so far but I've fixed a few things.

Can we get an English branch going?

**Comment by morais5** [comment]
My team is already taking care of that!

**Comment by CodeMeZone** [comment]
Awesome! I'll wait for it, any ETA?

**Comment by joransrb** [comment]
awesome!

**Comment by XXXTandem** [comment]
I'm currently working with Morais on an English translated version. Keep an eye on the discord we'll post it there once it's finished.

**Comment by morais5** [comment]
> I'm currently working with Morais on an English translated version. Keep an eye on the discord we'll post it there once it's finished.

👊🏻😉

**Comment by joransrb** [comment]
thats cool, care to share some mroe info on how you do it ? are you just going to translate the files directly or are you guys adding locale language support ? with locale files you would only need one codebase and it would make it easier to add and translate languages.

**Comment by XXXTandem** [comment]
I'm doing back and forth translation with google translate to figure out what everything is saying since I don't know any Portuguese

**Comment by joransrb** [comment]
> I'm doing back and forth translation with google translate to figure out what everything is saying since I don't know any Portuguese

i see... it would be better to go the "locale files" way, in regards of updates etc... but i guess that's up to @morais5 to implement as it requires some work.

**Comment by adamsimondev** [comment]
I'm working on the english translations in shared.lua. I've already added new images and numerous fixes. I will make a pull request later today.

**Comment by morais5** [comment]
> I'm working on the english translations in shared.lua. I've already added new images and numerous fixes. I will make a pull request later today.

Thanks man <3

**Comment by morais5** [comment]
Now all the base remains to be translated

**Comment by joransrb** [comment]
doing some translations, cant push or anything to your repo,
but here is what I've done so far: 
https://github.com/joransrb/QBCore-Morais/commit/719d3813597956139b69c5436ba10975e07180ca

**Comment by morais5** [comment]
> doing some translations, cant push or anything to your repo,
> but here is what I've done so far:
> [joransrb@719d381](https://github.com/joransrb/QBCore-Morais/commit/719d3813597956139b69c5436ba10975e07180ca)

make a pull requests plz thanks for help!

**Comment by joransrb** [comment]
done :) 
still some more to go
