### ISSUE TITLE
qb-cityhall error

### ISSUE THREAD

**Issue by XXXTandem** [morais5/QBCore-Morais#13]
After applying for a job in the menu th
![FiveM - Nos RP V2 2021-03-26 10_23_15 PM](https://user-images.githubusercontent.com/64930059/112707536-8f89d680-8e82-11eb-8305-f30fbbb8c554.png)
is error occured

**Comment by Zy0exe** [comment]
Money laundry isn't related to it as long as i know.
Just delete the "refreshPlayerWhitelisted"

**Comment by morais5** [comment]
Problem will be fixed in v4
