### ISSUE TITLE
qb-weapons loop.

### ISSUE THREAD

**Issue by Zy0exe** [morais5/QBCore-Morais#14]
--- look for
Citizen.CreateThread(function()
    while true do
        if IsControlJustReleased(0, 24) or IsDisabledControlJustReleased(0, 24) then
            local weapon = GetSelectedPedWeapon(GetPlayerPed(-1))
            local ammo = GetAmmoInPedWeapon(GetPlayerPed(-1), weapon)
            if ammo > 0 then
                TriggerServerEvent("weapons:server:UpdateWeaponAmmo", CurrentWeaponData, tonumber(ammo))
            else
                TriggerEvent('inventory:client:CheckWeapon')
                TriggerServerEvent("weapons:server:UpdateWeaponAmmo", CurrentWeaponData, 0)
            end

            if MultiplierAmount > 0 then
                TriggerServerEvent("weapons:server:UpdateWeaponQuality", CurrentWeaponData, MultiplierAmount)
                MultiplierAmount = 0
            end
        end
        Citizen.Wait(1)
    end
end)

-- change with
Citizen.CreateThread(function()
    while true do

        if IsControlJustReleased(0, 24) or IsDisabledControlJustReleased(0, 24) then
            local weapon = GetSelectedPedWeapon(GetPlayerPed(-1))
            local ammo = GetAmmoInPedWeapon(GetPlayerPed(-1), weapon)
            if weapon ~= GetHashKey("WEAPON_UNARMED") then
                if ammo > 0 then

                    TriggerServerEvent("weapons:server:UpdateWeaponAmmo", CurrentWeaponData, tonumber(ammo))
                    Citizen.Wait(500)
                else
                    TriggerEvent('inventory:client:CheckWeapon')
                    TriggerServerEvent("weapons:server:UpdateWeaponAmmo", CurrentWeaponData, 0)
                end

                
                if MultiplierAmount > 0 then
                    TriggerServerEvent("weapons:server:UpdateWeaponQuality", CurrentWeaponData, MultiplierAmount)
                    MultiplierAmount = 0
                end
            end

        end
        Citizen.Wait(0)
    end
end)

**Comment by morais5** [comment]
Done , Thanks <3

https://github.com/morais5/QBCore-Morais/blob/fce611e606618f7c0a7b0f6fdc57c4677a2b0657/server-data/resources/%5Bqb%5D/qb-weapons/client/main.lua#L120
