### ISSUE TITLE
qb-gangs

### ISSUE THREAD

**Issue by Zy0exe** [morais5/QBCore-Morais#16]
![image](https://user-images.githubusercontent.com/71949840/112739480-912fc900-8f6c-11eb-942b-6028c21b182a.png)

Fix
````ruby
fx_version "adamant"
game "gta5"
````

At this to the start of the fxmanifest.lua

**Comment by adamsimondev** [comment]
And delete this line:
`resource_manifest_version '44febabe-d386-4d18-afbe-5e627f4af937'`

**Comment by morais5** [comment]
done ! Thanks <3
