### ISSUE TITLE
qb-smallresources

### ISSUE THREAD

**Issue by Zy0exe** [morais5/QBCore-Morais#17]
![image](https://user-images.githubusercontent.com/71949840/112743612-a28acc80-8f90-11eb-92af-76fb3a15bcdf.png)
Sniper crosshair won't work with HideHudComponentThisFrame(14) because you're literally removing the hud component

The fix is pretty simple just comment out everything related with
````ruby
HideHudComponentThisFrame(14)
````

and put this in qb-smallresources/client/hudcomponents.lua
````ruby
Citizen.CreateThread(function()
    while true do
        if not IsAimCamActive() or not IsFirstPersonAimCamActive() then
            HideHudComponentThisFrame(14)
        end
        Citizen.Wait(0)
    end
end)
````
Should Look like this.
![image](https://user-images.githubusercontent.com/71949840/112743735-c0a4fc80-8f91-11eb-81b9-cdada80950d1.png)

Result:
![image](https://user-images.githubusercontent.com/71949840/112743751-eb8f5080-8f91-11eb-8dbc-2f28507baba5.png)
![image](https://user-images.githubusercontent.com/71949840/112743754-f649e580-8f91-11eb-8f14-1ffaffcab6d8.png)

**Comment by adamsimondev** [comment]
I made a pull request for this fix and added you as a co-author.

**Comment by Zy0exe** [comment]
> I made a pull request for this fix and added you as a co-author.

Alright, thank you.

**Comment by Zy0exe** [comment]
![image](https://user-images.githubusercontent.com/71949840/112762983-6f7d2300-8ffa-11eb-9f11-553fd5afc643.png)
This line still remains in density.lua

**Comment by morais5** [comment]
Done !

https://github.com/morais5/QBCore-Morais/blob/074e3de8cbee2118b578bcdd6a1e5245ad85c845/server-data/resources/%5Bqb%5D/qb-smallresources/client/density.lua#L21
