### ISSUE TITLE
lockpick does not work on bank doors or other

### ISSUE THREAD

**Issue by tnnuyri** [morais5/QBCore-Morais#6]
boas. o lockpick não esta a funcionar nas portas ,  nem na porta do banco

**Comment by morais5** [comment]
Irei ver o que se passa hoje mesmo!

**Comment by skizmx** [comment]
Same here, when I successfully opened the door with a lockpick and tried to enter the house, an error like this appeared

![Screenshot_4](https://user-images.githubusercontent.com/62847464/111925557-f6eb0380-8adb-11eb-830d-9abf1e5d3818.png)
